"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['DomainGetterUI.py']
DATA_FILES = ['/Library/Python/2.7/site-packages/whois',
 '/Library/Python/2.7/site-packages/xlsxwriter',
 '/Library/Python/2.7/site-packages/tkinter']
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/rishablal/dev/DomainGetter/assets/windowIcon'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
